#!/usr/bin/env node
// Stdio bridge for the hosted Transcodely MCP server.
//
// The real server lives at https://mcp.transcodely.com/mcp (streamable HTTP,
// browser OAuth). Clients that support remote servers should connect there
// directly. This bridge exists for stdio-only clients and headless use: it
// serves the hosted server's exact tool surface (vendored in ../tools.json,
// generated by the api's own `--dump-tools` export) and forwards tool calls to
// the hosted endpoint using a Transcodely API key from $TRANSCODELY_API_KEY.
//
// Note that set_spend_limit is served here and will always be refused: it needs
// an organization owner or admin signed in through the browser, and this bridge
// authenticates with an API key. That is the hosted server's rule, not the
// bridge's, so the tool stays listed and the refusal explains itself.
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StreamableHTTPClientTransport } from "@modelcontextprotocol/sdk/client/streamableHttp.js";
import {
  ListToolsRequestSchema,
  CallToolRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";

const ENDPOINT = process.env.TRANSCODELY_MCP_URL ?? "https://mcp.transcodely.com/mcp";
const API_KEY = process.env.TRANSCODELY_API_KEY;

const here = dirname(fileURLToPath(import.meta.url));

// One version for the bridge, the registry manifest and the tool surface —
// test/vendored.mjs holds package.json and server.json to the same string.
const BRIDGE_VERSION = JSON.parse(
  readFileSync(join(here, "..", "package.json"), "utf8"),
).version;
// tools.json is the api export: `{ server, tools }`, not a bare array.
const { tools } = JSON.parse(readFileSync(join(here, "..", "tools.json"), "utf8"));

const server = new Server(
  { name: "transcodely", version: BRIDGE_VERSION },
  { capabilities: { tools: {} } },
);

server.setRequestHandler(ListToolsRequestSchema, async () => ({ tools }));

let upstream;
async function upstreamClient() {
  if (upstream) return upstream;
  const client = new Client({ name: "transcodely-mcp-bridge", version: BRIDGE_VERSION });
  const transport = new StreamableHTTPClientTransport(new URL(ENDPOINT), {
    requestInit: { headers: { Authorization: `Bearer ${API_KEY}` } },
  });
  await client.connect(transport);
  upstream = client;
  return upstream;
}

server.setRequestHandler(CallToolRequestSchema, async (req) => {
  if (!API_KEY) {
    return {
      isError: true,
      content: [
        {
          type: "text",
          text:
            "No credentials: this bridge forwards to the hosted Transcodely MCP server, " +
            "which requires authentication. Either set TRANSCODELY_API_KEY (create a key " +
            "at https://www.transcodely.com) and restart, or — better, if your client " +
            "supports remote MCP servers — connect it directly to " +
            "https://mcp.transcodely.com/mcp and authorize in the browser.",
        },
      ],
    };
  }
  try {
    const client = await upstreamClient();
    return await client.callTool({ name: req.params.name, arguments: req.params.arguments ?? {} });
  } catch (err) {
    upstream = undefined; // force a fresh session on the next call
    return {
      isError: true,
      content: [{ type: "text", text: `Upstream call failed: ${err?.message ?? String(err)}` }],
    };
  }
});

await server.connect(new StdioServerTransport());
